find_library(
  LIBZMQ_LIBRARY
  NAMES zmq libzmq libzmq.so
  HINTS /usr/lib)

find_path(
  LIBZMQ_INCLUDE_DIR
  NAMES zmq.h
  HINTS /usr/include)
if(LIBZMQ_LIBRARY AND LIBZMQ_INCLUDE_DIR)
  set(LIBZMQ_FOUND TRUE)
endif(LIBZMQ_LIBRARY AND LIBZMQ_INCLUDE_DIR)
set(LIBZMQ_INCLUDE_DIRS ${LIBZMQ_INCLUDE_DIR})
set(LIBZMQ_LIBRARIES ${LIBZMQ_LIBRARY})
